construction and completion of the crud
TsunaHalo2001/Miniproyecto pull request #19
Opened 2024-11-06 19:59 UTC by DilanSanchez2004

2024-11-06 20:02 UTC, DilanSanchez2004 commented
¿Me podrías ayudar? es que hay un error en la linea 222 del App.java que no eh podido solucionar

2024-11-06 20:08 UTC, DilanSanchez2004 commented
y creo que también seria bueno que revisaras o probaras realizar accion y dar orden a ver que tal funciona.

2024-11-06 22:01 UTC, TsunaHalo2001 requested changes
Cambiar el crud respecto a lo solicitado

2024-11-06 22:01 UTC, TsunaHalo2001 commented on src/App.java
> +                                                ((Coronel) superior).realizarAccion((Capitan) subordinado);
Ninguno de los metodos realizarAccion deben ser usados en el programa principal, la idea es accederlo usando darOrden de cada superior

2024-11-06 23:19 UTC, TsunaHalo2001 requested changes

2024-11-06 23:19 UTC, TsunaHalo2001 commented on src/App.java
En la linea 124,  el constructor de SoldadoRaso esta mal implementado

2024-11-07 01:56 UTC, DilanSanchez2004 commented on src/App.java
El error ya a sido corregido

2024-11-07 02:21 UTC, TsunaHalo2001 approved these changes
Todo correcto

2024-11-07 02:21 UTC, merged